### ISSUE TITLE
Superdragon, Combat Knife, and Sniper Rifle Secondary Functions Bugged. RCP-120 glitched in a good way.

### ISSUE THREAD

**Issue by HeinrichVonStinkenfinger** [rafccq/perfect_dark#3]
If you use switch to the Superdragon and Combat Knife's secondary functions, then switch back to primary, the game gets soft locked and you're unable to change or use any weapons or gadgets, which is very bad for the levels A51 Rescue, A51 Escape, and Attack Ship. Also you are unable to crouch with the Sniper Rifle's secondary function, which harms your accuracy, though the crouching button still works with the Sniper Rifle!

The RCP-120 goes straight to Cloak mode if secondary button is pressed, but disables Cloak if pressed again. This is actually a helpful glitch and it's fix should be put on a toggle.

**Comment by rafccq** [comment]
The RCP going straight into cloak mode is actually a feature from the original port.
And the sniper rifle behavior is also the same as the original port, maybe we need to investigate later.
